### ISSUE TITLE
Area2D colliding with StaticBody2D - No Event 

### ISSUE THREAD

**Issue by VikingAntics** [godot-box2d/godot-box2d#19]
Hi, this is really cool and the physics seem 'better' than the default Godot 2D.

I am having an issue with getting any signals i.e. _on_body_entered() when an Area2D collides with a StaticBody2D.
It works fine with the Godot 2D Physics, but not with Box2D.  Not sure if I am doing something wrong or this is a bug, or just the way Box2D works.

Thanks,

**Comment by Ughuuu** [comment]
Thanks for reporting it. Will look into it.

**Comment by Ughuuu** [comment]
Disregard previous comment. Doesn't seem to be related.
Can you upload a project where you can reproduce this specific case? That would help a lot.(I have stumbled another issue I am trying to fix, but area and staticbody2d works for me).

**Comment by VikingAntics** [comment]
Thanks for your response.  It may be related to the fact that I am moving the Area2D with position * delta * speed, however, it does work with the default & GodotPhysics2D modules.  I am always sensitive to the fact that I am doing something wrong. ;-)

Here is a simple example project.  The Area2D is being moved manually using the transform position and when it collides with the StaticBody2D, no signals are being emitted.  Using the built-in physics modules, it reports a body_entered signal.  

Thank you for taking the time to look at this situation!


[Box2D_Area2D_StaticBody2D.zip](https://github.com/godot-box2d/godot-box2d/files/12207895/Box2D_Area2D_StaticBody2D.zip)

**Comment by Ughuuu** [comment]
I tested with https://github.com/godot-box2d/godot-box2d/pull/20 and it seems to have fixed it. Will make a release and let you know when you can test.

**Comment by VikingAntics** [comment]
Ughuuu, that seems to have fixed it!!!  Thank you very much for your help.  I have to say, the physics with Box2D are just much better in certain circumstances.  I have some RigidBody2Ds falling to the ground (StaticBody2D) and the collisions when they bump into each other and bounce around are far better with Box2D.  Thank you again.
