### ISSUE TITLE
Does this add-on support deterministic physics?

### ISSUE THREAD

**Issue by Calinou** [godot-box2d/godot-box2d#21]
Out of curiosity, does Box2D (and this Godot integration) support deterministic physics? This should be noted in the README (even if it isn't), as this may be a reason to look for a third-party physics engine.

**Comment by Ughuuu** [comment]
Will add to the readme.

Right now, it only has binary determinism. Box2c(the next version of box2d or box2d v3) will have also threaded determinism and support for multithreaded physics using tasks from godot.
Not 100% sure about the roadmap of erin, the creator of box2d, about adding cross platform determinism, if that is important to godot or not.
